### ISSUE TITLE
Image src not replaced

### ISSUE THREAD

**Issue by dev0x10** [Foxandxss/angular-webpack-workflow#5]
I have a directive with img src='image1.jpg' tag inside it.
The image file was compiled but the img src content not changed.
I understand that ES6 style with Angular 1.x still has a problem with directive.
I'm using one of the available solution, creating a static function and return directive instance

```javascript
static directiveFactory($http, $location) {
    TopNavDir.instance = new TopNavDir($http, $location);
    return TopNavDir.instance;
  }
```

I'm  wondering whether the img src not changed because of angular directive problem with ES6 style

**Comment by Foxandxss** [comment]
The problem is that webpack is that you need to require everything, that include images.

So one solution would be to do a `require(...)` for every image you template have (and probably disable the cache on them).

Another solution is to have inline templates so you can do stuff like:

```
var img = require('img.jpg');

...
template: `<img src="${img}" />`
...
```

Or if you have all your images in a static folder for example, you can move that with a script to the `/public` folder so it will find the images.

**Comment by dev0x10** [comment]
ah i see....
Thanks!!
