### ISSUE TITLE
after updating html-webpack-plugin to the latest version template file stopped working

### ISSUE THREAD

**Issue by LiorSaadon** [Foxandxss/angular-webpack-workflow#6]
Can you provide an example on how to use the new templating that was intereduced in the latest version of  "html-webpack-plugin".
i can't make it it work since i updated from version 1.6.2

this is my index.html:

<!doctype html>
< html>
< head>
  < meta charset="UTF-8">
  < title><%- htmlWebpackPlugin.options.title %>< /title>

</ head>
< body>
< div class="container">
  < ui-view></ ui-view>
< /div>

< /body>
< /html>

and my webpack.make.js file is similar to yours:
            new HtmlWebpackPlugin({
                filename: 'index-dev.html',
                template: './src/index.html',
                inject: true,
                dev: true,
                title: 'Dev mode'
            })

**Comment by Foxandxss** [comment]
The author of that library loves the breaking changes without changelogs.
I'll check that when I get home.

**Comment by Foxandxss** [comment]
I see you opened an issue there, so I am closing this one.

**Comment by LiorSaadon** [comment]
what do you mean ? i will be happy to get some kind of help i didn't open an issue

**Comment by Foxandxss** [comment]
Your issue is about html-webpack-plugin so it is better if you talk with its author. I don't really have the response you need.

And on the other hand, I saw you opening an issue there: https://github.com/ampedandwired/html-webpack-plugin/issues/193 so we can continue there.

**Comment by LiorSaadon** [comment]
Ok, thanks.
btw i appreciate the work you did with this workflow, good job

**Comment by jantimon** [comment]
@Foxandxss well there is a big breaking change from 1.x to 2.x which is documented in the migration guide. Take a look at http://semver.org/

**Comment by Foxandxss** [comment]
Thanks for the reply @jantimon . I didn't see that migration guide (I always check for changelog / history and yours was incomplete). I just bumped the version, tried the workflow and it was working correctly. I am pretty aware how semver works and sorry for the last comment, but the minify unexpected change broke the workflow not long ago.

That being said and if I understood correctly, by default my template should support lodash templating (since I am not using html-loader).

My need for html-weboack-plugin for this workflow is just to support cache busting. It is really handy because it will add all the bundles and css into the html without needed manual interaction. I am not really using any extra template usage (lodash / handlebars / jade / ...) so that is why I redirected @LiorSaadon to the main repo, he could get more help in here.

So if my configuration is broken I will surely fix it and if what he needs is just an extra package or added config for needs, I guess he could simply put it. I just want to give a sane defaults.

Keep up the work on the plugin @jantimon I really like it, and consider using a changelog generator (https://github.com/ajoslin/conventional-changelog) so you can automatically generate a changelog every time you push a new release :)

**Comment by jantimon** [comment]
I also thought about using https://github.com/semantic-release/semantic-release which uses conventional-changelog however I don't have admin privileges for the html plugin.

The html webpack plugin now uses the webpack compiler to support loaders.
That means that webpack will apply all loaders found in your main config also for the compilation of the template. (this is done by webpack not by the webpack-html-plugin) to prevent this you might rename your template to index.ejs or index.tpl:

```
      new HtmlWebpackPlugin({
        template: './src/index.html',
        inject: 'body'
      })
```

will trigger:

```
      // HTML LOADER
      // Reference: https://github.com/webpack/raw-loader
      // Allow loading html through js
      test: /\.html$/,
      loader: 'raw' 
```

Otherwise just stick to the 1.x branch.

**Comment by Foxandxss** [comment]
Thank you, I follow your idea now.

The thing is, even if that loader runs, I get the desired output and everything works fine (also tried renaming to .tpl and works exactly the same).

So I guess that unless some issue arises, I will leave it as is.

**Comment by jantimon** [comment]
Oh - you aren't using any lodash variables anyway.. Then you are correct - it should also work with `.html`.
